services:
  prometheus: # Servicio de Prometheus para monitoreo y recolección de métricas
    image: prom/prometheus:latest
    container_name: inventory_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana: # Servicio de Grafana para visualización de métricas
    image: grafana/grafana:latest
    container_name: inventory_grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-admin}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
      - loki
      - tempo
    restart: unless-stopped

  loki: # Servicio de recolección de logs centralizados
    image: grafana/loki:latest
    container_name: inventory_loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped

  tempo: # Servicio de recolección de trazas distribuidas
    image: grafana/tempo:latest
    container_name: inventory_tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    ports:
      - "3200:3200"
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
    restart: unless-stopped

  alloy: # Grafana Alloy como recolector y enrutador principal de telemetría (OTel Collector)
    image: grafana/alloy:latest
    container_name: inventory_alloy
    ports:
      - "4317:4317" # OTLP gRPC para backend (Mapeado al host para que app/backend lo vea)
      - "4318:4318" # OTLP HTTP
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - /etc/alloy/config.alloy
    depends_on:
      - loki
      - tempo
    restart: unless-stopped

volumes:
  grafana_data: